import 'package:get/get_navigation/src/root/internacionalization.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSub':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSendTo': "Code has been send to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSub':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSub':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSub':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSub': "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSub':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSub':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSub':
              "To use this service, we need permission to access your photos.",
        },
        'es': {
          'welcomeHeading': "Welcome to Tiqarte!",
          'welcomeSub':
              "The best event booking and online ticketing application in this century.",
          'getStarted1Heading': "Grab all events now only in your hands",
          'getStarted1Sub':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted2Heading': "Easy payment & fast event ticketing",
          'getStarted2Sub':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3Heading': "Let's go to your favorite event right now!",
          'getStarted3Sub':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3Button': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSub':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSendTo': "Code has been send to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSub':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSub':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSub':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSub': "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSub':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Idioma",
          'darkMode': "Modo oscuro",
          'helpCenter': "Centro de ayuda",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSub':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSub':
              "To use this service, we need permission to access your photos.",
        },
        'de': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSub':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSendTo': "Code has been send to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSub':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSub':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSub':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSub': "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSub':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSub':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSub':
              "To use this service, we need permission to access your photos.",
        },
        'fr': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSub':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSendTo': "Code has been send to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSub':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSub':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSub':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSub': "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSub':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSub':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSub':
              "To use this service, we need permission to access your photos.",
        },
        'it': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSub':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSendTo': "Code has been send to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSub':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSub':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSub':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSub':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSub': "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSub':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSub':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSub':
              "To use this service, we need permission to access your photos.",
        },
      };
}
