import 'package:get/get_navigation/src/root/internacionalization.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSubString':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSentTo': "Code has been sent to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSubString':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSubSrting':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSubString':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSubSrting':
              "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'city': 'City',
          'zipcode': 'Zip code',
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSubSrting':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSubString':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSubString':
              "To use this service, we need permission to access your photos.",
        },
        'es': {
          'welcomeHeading': "¡Bienvenido/a a Tiqarte!",
          'welcomeSubString':
              "La mejor aplicación de reserva de eventos y venta de entradas.",
          'getStarted1HeadingString':
              "Accede a todos los eventos ahora, todo en tus manos",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': 'Siguiente',
          'getStarted2HeadingString':
              "Pago fácil y venta rápida de entradas para eventos",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "¡Vayamos a tu evento favorito ahora mismo!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Comenzar",
          'letsYouIn': "Vamos a entrar",
          'continueWithFacebook': "Continuar con Facebook",
          'continueWithGoogle': "Continuar con Google",
          'continueWithApple': "Continuar con Apple",
          'or': "Ó",
          'dontHaveAccount': "¿No tienes una cuenta?",
          'signWithPassword': "Iniciar sesión con contraseña",
          'signUp': "Regístrate",
          'createNewAccount': "Crear nueva cuenta",
          'password': "Contraseña",
          'rememberMe': "Recuérdame",
          'orContinueWith': "o continuar con",
          'alreadyHaveAccount': "¿Ya tienes una cuenta?",
          'signIn': "Iniciar sesión",
          'logIntoYourAccount': "Accede a tu cuenta",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "¿Olvidaste tu contraseña?",
          'forgotPasswordSubString':
              "Selecciona qué detalles de contacto deberíamos usar para restablecer tu contraseña.",
          'viaSMS': "A través de SMS:",
          'viaEmail': "A través de correo electrónico:",
          'otpCodeVerification': "Verificación de código OTP",
          'codeHasBeenSentTo': "El código ha sido enviado a ",
          'resendCodeIn': "Reenviar el código en ",
          'resend': "Reenviar",
          'verify': "Verificar",
          'createNewPassword': "Crear nueva contraseña",
          'createYourNewPassword': "Crea tu nueva contraseña",
          'enterNewPassword': "Ingresa nueva contraseña",
          'confirmPassword': "Confirmar contraseña",
          'newPasswordCongratsSubString':
              "Tu cuenta está lista para utilizarse. Serás redirigido a la página de inicio en unos segundos...",
          'setYourLocation': "Configura tu ubicación",
          'congratulations': "¡Felicidades!",
          'locationSetupDialogSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Inicio",
          'explore': "Explorar",
          'favorites': "Favoritos",
          'tickets': "Entradas",
          'profile': "Perfil",
          'all': "Todos",
          'music': "Música",
          'art': "Arte",
          'workshops': "Talleres",
          'found': "Encontrado",
          'foundSubString':
              "Lo siento, la palabra clave que ingresaste no se puede encontrar. Por favor, verifica de nuevo o busca con otra palabra clave.",
          'filter': "Filtrar",
          'eventCategory': "Categoría del evento",
          'eventLocationRange': "Rango de ubicación del evento (km)",
          'reset': "Restablecer",
          'apply': "Aplicar",
          'notification': "Notificación",
          'notificationSubSrting':
              "No tienes ninguna notificación en este momento",
          'upcoming': "Próximos",
          'completed': "Completados",
          'cancelled': "Cancelados",
          'paid': "Pagados",
          'ticketReviewSubString':
              "¿Cómo fue tu experiencia con la formación de Arte y Pintura?",
          'emptyTickets': "Entradas vacías",
          'emptyTicketsSubString':
              "Parece que aún no tienes una entrada. Comienza a buscar eventos ahora haciendo clic en el botón de abajo",
          'findEvents': "Buscar eventos",
          'cancelBooking': "Cancelar compra",
          'cancelBookingSubString':
              "¿Estás seguro de que deseas anular esta compra?",
          'ticketCancelBookingRefund':
              "Solo el 80% de los fondos se devolverán a tu cuenta según nuestra política.",
          'noDontCancel': "No, no cancelar",
          'yesCancel': "Sí, cancelar",
          'pleaseSelectTheReasonForcancellation':
              "Por favor, selecciona el motivo de la cancelación:",
          'IHaveAnotherEventSoItCollides':
              "Tengo otro evento, así que coinciden",
          'imSickCantCome': "Estoy enfermo/a, no puedo asistir",
          'iHaveAnUrgentNeed': "Tengo una necesidad urgente	",
          'iHaveNoTransportationToCome': "No tengo transporte para ir",
          'iHaveNoFriendsToCome': "No tengo amigos para ir",
          'iWantToBookAnotherEvent': "Quiero acudir a otro evento",
          'iJustWantToCancel': "Simplemente quiero cancelar",
          'others': "Otros	",
          'otherReason': "Otros motivos...",
          'successful': "¡Éxito!",
          'ok': "Aceptar",
          'favorite': "Favorito",
          'removeFromFavorites': "¿Eliminar de Favoritos?",
          'yesRemove': "Sí, eliminar",
          'goodMorning': "Buenos días",
          'goodAfternoon': 'buenas tardes',
          'goodEvening': 'buenas noches',
          'goodNight': 'buenas noches',
          'whatEventAreYouLookingFor': "¿Qué evento estás buscando?...",
          'featured': "Destacados",
          'fillYourProfile': "Completa tu perfil",
          'fullName': "Nombre completo",
          'state': "Dirección",
          'city': 'ciudad',
          'zipcode': 'código postal',
          'postalCode': "Código postal",
          'nickName': "Nick",
          'dateOfBirth': "Fecha de nacimiento",
          'email': "Correo electrónico",
          'gender': "Género",
          'male': "Masculino",
          'female': "Femenino",
          'other': "Otro",
          'addToMyCalender': "Añadir a mi calendario",
          'seeLocationOnMaps': "Ver ubicación en el mapa",
          'follow': "Seguir",
          'following': "Siguiendo",
          'phone': "Teléfono",
          'aboutEvent': "Sobre el evento",
          'readMore': "Leer más...",
          'showLess': "Mostrar menos",
          'galleryPreEvent': "Galería (Pre-Evento)",
          'seeAll': "Ver todos",
          'location': "Ubicación",
          'moreEventsLikeThis': "Más eventos como este",
          'bookEvent': "Comprar entrada",
          'eventLocation': "Ubicación del evento",
          'getDirection': "Obtener indicaciones",
          'direction': "Indicaciones",
          'organizer': "Organizador",
          'event': "Evento",
          'events': "Eventos",
          'followers': "Seguidores",
          'message': "Mensaje",
          'collections': "Colecciones",
          'about': "Acerca de",
          'free': "Gratis",
          'economy': "Económica",
          'vip': "VIP",
          'seat': "Asiento",
          'chooseNumberOfSeats': "Elige el número de asientos",
          'continueButton': "Continuar",
          'contactInformation': "Información de contacto",
          'iAcceptTheEveno': "Acepto los Términos de servicio de Tiqarte",
          'termsOfService': "Términos del Servicio",
          'communityGuidelines': "Directrices Comunes",
          'and': "y",
          'privacyPolicy': "Política de Privacidad",
          'require': "(Requerido)",
          'payments': "Pagos",
          'selectThePaymentMethod':
              "Selecciona el método de pago que deseas usar",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Agregar nueva tarjeta",
          'cardHolderName': "Nombre del titular de la tarjeta",
          'cardName': "Nombre de la Tarjeta",
          'cardNumber': "Número de la Tarjeta",
          'expiryDate': "Fecha de Vencimiento",
          'cvv': "CVV",
          'add': "Agregar",
          'reviewSummary': "Revisar Resumen",
          'total': "Total",
          'tax': "Impuesto",
          'change': "Cambiar",
          'enterYourPin': "Introduce tu PIN",
          'enterYourPinToConfirm': "Introduce tu PIN para confirmar el pago",
          'viewETicket': "Ver Entrada",
          'eTicket': "Entrada",
          'cancel': "Cancelar",
          'successPlaceOrderEvent':
              "Has realizado con éxito un pedido para el Festival Nacional de Música. ¡Disfruta del evento!",
          'failedPlaceOrder':
              "Tu pago falló. Por favor, verifica tu conexión a Internet y luego intentalo nuevamente.",
          'tryAgain': "Intentar de nuevo",
          'oopsFaild': "¡Vaya, falló!",
          'downloadTicket': "Descargar entrada",
          'country': "País",
          'paymentMethods': "Métodos de pago",
          'orderID': "ID de pedido",
          'status': "Estado",
          'dateAndHour': "Fecha y hora",
          'eventOrganizer': "Organizador del evento",
          'enableLocation': "Activar ubicación",
          'locationDialogSubString':
              "Para usar este servicio, necesitamos permiso para acceder a tu ubicación.",
          'manageEvents': "Administrar eventos",
          'messageCenter': "Centro de mensajes",
          'linkedAccounts': "Cuentas vinculadas",
          'ticketIssues': "Problemas con las entradas",
          'security': "Seguridad",
          'language': "Idioma",
          'darkMode': "Modo oscuro",
          'helpCenter': "Centro de ayuda",
          'inviteFriends': "Invitar amigos",
          'invite': "Invitar",
          'invited': "Invitado",
          'rateUs': "Valoraciones",
          'logout': "Cerrar sesión",
          'EnableSoundVibrate': "Activar sonido y vibración",
          'purchasedTickets': "Entradas compradas",
          'likedEvents': "Eventos que te gustaron",
          'followedOrganizer': "Organizadores seguidos",
          'specialOffers': "Ofertas especiales",
          'reminders': "Recordatorios",
          'recommendations': "Recomendaciones",
          'appUpdates': "Actualizaciones de la aplicación",
          'newServiceAvailable': "Nuevo servicio disponible",
          'newTipsAvailable': "Nuevos consejos disponibles",
          'faceID': "ID de rostro",
          'biometricID': "ID biométrico",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "Preguntas frecuentes",
          'contactUs': "Contáctanos",
          'general': "General",
          'account': "Cuenta",
          'service': "Servicio",
          'payment': "Pago",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Conectado",
          'changePIN': "Cambiar PIN",
          'changePassword': "Cambiar contraseña",
          'suggested': "Sugerido",
          'customerService': "Atención al cliente",
          'whatsApp': "WhatsApp",
          'website': "Sitio web",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "¿Estás seguro de que quieres cerrar sesión?",
          'yesLogout': "Sí, cerrar sesión",
          'leaveAReview': "Deja una reseña",
          'alreadyReviewed': "Ya revisados",
          'leaveAReviewSub':
              "¿Cómo fue tu experiencia con la Formación de Arte y Pintura?",
          'writeYourReview': "Escribe tu reseña",
          'yourReviewHere': "Tu reseña aquí...",
          'maybeLater': "Tal vez después",
          'submit': "Enviar",
          'upcomingEvent': "Próximos Eventos",
          'shop': "Tienda",
          'forMen': "para Hombres",
          'forWomen': "para Mujeres",
          'description': "Descripción",
          'deliveryDetails': "Detalles de entrega",
          'moreLikeThis': "Más como esto",
          'addtoBasket': "Agregar al carrito",
          'outOfStock': "Agotado",
          'size': "Talla",
          'color': "Color",
          'myBasket': "Mi cesta",
          'item': "Artículo",
          'remove': "Eliminar",
          'quantity': "Cantidad",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Los gastos de envío e impuestos se calculan al finalizar la compra.",
          'checkout': "Pagar",
          'contactDetail': "Detalles de contacto",
          'continuetoPayment': "Continuar con el pago",
          'done': "Hecho",
          'shopMore': "Comprar más",
          'notFound': "No encontrado",
          'empty': "Vacío",
          'search': "Buscar",
          'alert': "Alerta",
          'error': "Error",
          'totalItem': "Total de artículos",
          'totalAmount': "Monto total",
          'pleaseEnterPassword': "Por favor, introduce la contraseña",
          'pleaseEnterEmail': "Por favor, introduce el correo electrónico",
          'pleaseEnterValidEmail':
              "Por favor, introduce un correo electrónico válido",
          'camera': "Cámara",
          'gallery': "Galería",
          'somethingWentWrong': "Algo salió mal",
          'placeOrderSuccess':
              "¡Has realizado con éxito un pedido para la camiseta con cuello clásico!",
          'enableCamera': "Activar cámara",
          'enableCameraSubString':
              "Para usar este servicio, necesitamos permiso para acceder a tu cámara.",
          'enablePhoto': "Activar foto",
          'enablePhotoSubString':
              "Para usar este servicio, necesitamos permiso para acceder a tus fotos.",
        },
        'de': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSubString':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSentTo': "Code has been sent to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSubString':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSubSrting':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSubString':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSubSrting':
              "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'city': 'City',
          'zipcode': 'Zip code',
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSubSrting':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSubString':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSubString':
              "To use this service, we need permission to access your photos.",
        },
        'fr': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSubString':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSentTo': "Code has been sent to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSubString':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSubSrting':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSubString':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSubSrting':
              "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'city': 'City',
          'zipcode': 'Zip code',
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSubSrting':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSubString':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSubString':
              "To use this service, we need permission to access your photos.",
        },
        'it': {
          'welcomeHeadingString': "Welcome to Tiqarte!",
          'welcomeSubString':
              "The best event booking and online ticketing application in this century.",
          'getStarted1HeadingString': "Grab all events now only in your hands",
          'getStarted1SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'next': "Next",
          'getStarted2HeadingString': "Easy payment & fast event ticketing",
          'getStarted2SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted3HeadingString':
              "Let's go to your favorite event right now!",
          'getStarted3SubString':
              "This is a detail text place.This is a detail text place.This is a detail text place.This is a detail text place.",
          'getStarted': "Get Started",
          'letsYouIn': "Let's you in",
          'continueWithFacebook': "Continue with Facebook",
          'continueWithGoogle': "Continue with Google",
          'continueWithApple': "Continue with Apple",
          'or': "Or",
          'dontHaveAccount': "Don't have an account?",
          'signWithPassword': "Sign in with password",
          'signUp': "Sign up",
          'createNewAccount': "Create New Account",
          'password': "Password",
          'rememberMe': "Remember me",
          'orContinueWith': "or continue with",
          'alreadyHaveAccount': "Already have an account?",
          'signIn': "Sign in",
          'logIntoYourAccount': "Login to Your Account",
          'forgotThePassword': "Forgot the password?",
          'forgotPassword': "Forgot Password",
          'forgotPasswordSubString':
              "Select which contact details should we use to reset your password",
          'viaSMS': "via SMS:",
          'viaEmail': "via Email:",
          'otpCodeVerification': "OTP Code Verification",
          'codeHasBeenSentTo': "Code has been sent to ",
          'resendCodeIn': "Resend code in ",
          'resend': "Resend",
          'verify': "Verify",
          'createNewPassword': "Create New Password",
          'createYourNewPassword': "Create Your New Password",
          'enterNewPassword': "Enter new password",
          'confirmPassword': "Confirm Password",
          'newPasswordCongratsSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'setYourLocation': "Set Your Location",
          'congratulations': "Congratulations!",
          'locationSetupDialogSubString':
              "Your account is ready to use. You will be redirected to the Home page in a few seconds..",
          'home': "Home",
          'explore': "Explore",
          'favorites': "Favorites",
          'tickets': "Tickets",
          'profile': "Profile",
          'all': "All",
          'music': "Music",
          'art': "Art",
          'workshops': "Workshops",
          'found': "Found",
          'foundSubString':
              "Sorry, the keyword you entered cannot be found, please check again or search with another keyword.",
          'filter': "Filter",
          'eventCategory': "Event Category",
          'eventLocationRange': "Event Location Range (km)",
          'reset': "Reset",
          'apply': "Apply",
          'notification': "Notification",
          'notificationSubSrting':
              "You don't have any notifications at this time",
          'upcoming': "Upcoming",
          'completed': "Completed",
          'cancelled': "Cancelled",
          'paid': "Paid",
          'ticketReviewSubSrting':
              "How was your experience withArt & Painting Training?",
          'emptyTickets': "Empty Tickets",
          'emptyTicketsSubString':
              "Looks like you don't have a ticket yet.Start searching for events now by clicking the button below.",
          'findEvents': "Find Events",
          'cancelBooking': "Cancel Booking",
          'cancelBookingSubSrting':
              "Are you sure you want to cancel this event?",
          'ticketCancelBookingRefund':
              "Only 80% of funds will be returned to your account according to our policy.",
          'noDontCancel': "No, Don't Cancel",
          'yesCancel': "Yes, Cancel",
          'pleaseSelectTheReasonForcancellation':
              "Please select the reason for cancellation:",
          'IHaveAnotherEventSoItCollides':
              "I have another event, so it collides",
          'imSickCantCome': "I'm sick, can't come",
          'iHaveAnUrgentNeed': "I have an urgent need",
          'iHaveNoTransportationToCome': "I have no transportation to come",
          'iHaveNoFriendsToCome': "I have no friends to come",
          'iWantToBookAnotherEvent': "I want to book another event",
          'iJustWantToCancel': "I just want to cancel",
          'others': "Others",
          'otherReason': "Others reason...",
          'successful': "Successful!",
          'ok': "OK",
          'favorite': "Favorite",
          'removeFromFavorites': "Remove from Favorites?",
          'yesRemove': "Yes, Remove",
          'goodMorning': "Good Morning",
          'whatEventAreYouLookingFor': "What event are you looking for...",
          'featured': "Featured",
          'fillYourProfile': "Fill Your Profile",
          'fullName': "Full Name",
          'state': "State",
          'city': 'City',
          'zipcode': 'Zip code',
          'postalCode': "Postal Code",
          'nickName': "Nickname",
          'dateOfBirth': "Date of Birth",
          'email': "Email",
          'gender': "Gender",
          'male': "Male",
          'female': "Female",
          'other': "Other",
          'addToMyCalender': "Add to My Calendar",
          'seeLocationOnMaps': "See Location on Maps",
          'follow': "Follow",
          'following': "Following",
          'phone': "Phone",
          'aboutEvent': "About Event",
          'readMore': "Read more...",
          'showLess': "Show Less",
          'galleryPreEvent': "Gallery (Pre-Event)",
          'seeAll': "See All",
          'location': "Location",
          'moreEventsLikeThis': "More Events like this",
          'bookEvent': "Book Event",
          'eventLocation': "Event Location",
          'getDirection': "Get Direction",
          'direction': "Direction",
          'organizer': "Organizer",
          'event': "Event",
          'events': "Events",
          'followers': "Followers",
          'message': "Message",
          'collections': "Collections",
          'about': "About",
          'free': "Free",
          'economy': "Economy",
          'vip': "VIP",
          'seat': "Seat",
          'chooseNumberOfSeats': "Choose number of seats",
          'continueButton': "Continue",
          'contactInformation': "Contact Information",
          'iAcceptTheEveno': "I accept the Tiqarte",
          'termsOfService': "Terms of Service",
          'communityGuidelines': "Community Guidelines",
          'and': "and",
          'privacyPolicy': "Privacy Policy",
          'require': "(Required)",
          'payments': "Payments",
          'selectThePaymentMethod':
              "Select the payment method you want to use.",
          'payPal': "PayPal",
          'googlePay': "Google Pay",
          'applePay': "Apple Pay",
          'addNewCard': "Add New Card",
          'cardHolderName': "Card Holder name",
          'cardName': "Card Name",
          'cardNumber': "Card Number",
          'expiryDate': "Expiry Date",
          'cvv': "CVV",
          'add': "Add",
          'reviewSummary': "Review Summary",
          'total': "Total",
          'tax': "Tax",
          'change': "Change",
          'enterYourPin': "Enter Your Pin",
          'enterYourPinToConfirm': "Enter your PIN to confirm payment",
          'viewETicket': "View E-Ticket",
          'eTicket': "E-Ticket",
          'cancel': "Cancel",
          'successPlaceOrderEvent':
              "You have successfully placed an order for National Music Festival. Enjoy the event!",
          'failedPlaceOrder':
              "Your payment failed. Please check your internet connection then try again.",
          'tryAgain': "Try Again",
          'oopsFaild': "Oops, Failed!",
          'downloadTicket': "Download Ticket",
          'country': "Country",
          'paymentMethods': "Payment Methods",
          'orderID': "Order ID",
          'status': "Status",
          'dateAndHour': "Date and Hour",
          'eventOrganizer': "Event Organizer",
          'enableLocation': "Enable Location",
          'locationDialogSubSrting':
              "To use this service, we need permission to access your location.",
          'manageEvents': "Manage Events",
          'messageCenter': "Message Center",
          'linkedAccounts': "Linked Accounts",
          'ticketIssues': "Ticket Issues",
          'security': "Security",
          'language': "Language",
          'darkMode': "Dark Mode",
          'helpCenter': "Help Center",
          'inviteFriends': "Invite Friends",
          'invite': "Invite",
          'invited': "Invited",
          'rateUs': "Rate us",
          'logout': "Logout",
          'EnableSoundVibrate': "Enable Sound & Vibrate",
          'purchasedTickets': "Purchased Tickets",
          'likedEvents': "Liked Events",
          'followedOrganizer': "Followed Organizer",
          'specialOffers': "Special Offers",
          'reminders': "Reminders",
          'recommendations': "Recommendations",
          'appUpdates': "App Updates",
          'newServiceAvailable': "New Service Available",
          'newTipsAvailable': "New Tips Available",
          'faceID': "Face ID",
          'biometricID': "Biometric ID",
          'googleAuthenticator': "Google Authenticator",
          'fAQ': "FAQ",
          'contactUs': "Contact us",
          'general': "General",
          'account': "Account",
          'service': "Service",
          'payment': "Payment",
          'google': "Google",
          'facebook': "Facebook",
          'apple': "Apple",
          'connected': "Connected",
          'changePIN': "Change PIN",
          'changePassword': "Change Password",
          'suggested': "Suggested",
          'customerService': "Customer Service",
          'whatsApp': "WhatsApp",
          'website': "Website",
          'twitter': "Twitter",
          'instagram': "Instagram",
          'logoutSub': "Are you sure you want to log out?",
          'yesLogout': "Yes, Logout",
          'leaveAReview': "Leave a Review",
          'alreadyReviewed': "Already Reviewed",
          'leaveAReviewSub':
              "How was your experience with Art & Painting Training?",
          'writeYourReview': "Write Your Review",
          'yourReviewHere': "Your review here...",
          'maybeLater': "Maybe Later",
          'submit': "Submit",
          'upcomingEvent': "Upcoming Event",
          'shop': "Shop",
          'forMen': "for Men",
          'forWomen': "for Women",
          'description': "Description",
          'deliveryDetails': "Delivery details",
          'moreLikeThis': "More like this",
          'addtoBasket': "Add to basket",
          'outOfStock': "Out of stock",
          'size': "Size",
          'color': "Color",
          'myBasket': "My basket",
          'item': "item",
          'remove': "Remove",
          'quantity': "Quantity",
          'subtotal': "Subtotal",
          'shippingTaxesAtCheckout':
              "Shipping & taxes are calculated at checkout",
          'checkout': "Checkout",
          'contactDetail': "Contact details",
          'continuetoPayment': "Continue to payment",
          'done': "Done",
          'shopMore': "Shop More",
          'notFound': "Not Found",
          'empty': "Empty",
          'search': "Search",
          'alert': "Alert",
          'error': "Error",
          'totalItem': "Total Item",
          'totalAmount': "Total Amount",
          'pleaseEnterPassword': "Please enter password",
          'pleaseEnterEmail': "Please enter email",
          'pleaseEnterValidEmail': "Please enter a valid email",
          'camera': "Camera",
          'gallery': "Gallery",
          'somethingWentWrong': "Something went wrong",
          'placeOrderSuccess':
              "You have successfully placed an order for Classic pullover t-shirt.!",
          'enableCamera': "Enable Camera",
          'enableCameraSubString':
              "To use this service, we need permission to access your camera.",
          'enablePhoto': "Enable Photo",
          'enablePhotoSubString':
              "To use this service, we need permission to access your photos.",
        },
      };
}
